config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  get 'users/profile'

  get 'rooms/home'

  devise_for :users
  get 'pages/home'
  get 'rooms/new'
  get 'reservations/index'
  get 'rooms/index'
  get 'users/login'


  resources :rooms do
    collection do
      get 'serch'
    end
  end

  resources :pages do
    collection do
      get 'home'
    end
  end

  resources :users
  resources :reservations
  resources :rooms

  resources :rooms do
    resources :reservations
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :image
         validates :name, presence: true
         validates :email, uniqueness: true, presence: true

  has_many :rooms
  has_many :reservations
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
  #   super
   end

  # POST /resource
  def create
  #   super


   end
   def after_sign_up_path_for(resource)
    flash[:notice] = "新規登録完了しました。次に名前を入力してください"
    rooms_home_path
  end


  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  def after_sign_out_path_for(resource)
    flash[:notice] = "ログアウトしました"
    pages_home_path
  end
  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def account
    @user = current_user
  end
  def profile
    @user = current_user
  end

  def login
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
    @user = current_user

    end
  def update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:image, :name ,:profile))
      flash[:notice]="更新しました"
      redirect_back(fallback_location: users_profile_path)
    else
      flash.now[:notice]="更新に失敗してしまいました、再入力してください"
      redirect_back(fallback_location: users_profile_path)
    end
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="container-fiuld user">
    <div class="row">


        <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
            <ul>
                <li class="active">
                    <%= link_to "プロフィール",users_profile_path %>
                </li>
            </ul>
        </div>


                <%= form_with model: @user, url: users_path,  class: 'new_user', local: true do |f| %>

                <div class="update-content">
                    <div class="row">
                        <%= f.label :メールアドレス,class:"col-md-3" %><br />
                        <div class="col-md-9"><%= @user.email %></div>

                    </div>
                </div>

                <div class="update-content">
                    <div class="row">
                        <%= f.label :パスワード,class:"col-md-3" %><br />
                        <div class="col-md-9">********</div>
                    </div>
                </div>

                <div class="update-content"></div>
                    <div class="row">
                        <%= link_to "編集", users_profile_path,class:"col-md-2 btn btn-primary mx-3"%>
                    </div>
                </div>

                <% end %>

            </div>
        </div>
    </div>
</div>

app/views/users/login.html.erb
<div class="top">
    <div class="top-main">
        <div class="container">
            <div class="row col-lg-6">
                <div class="form-fream">
                    <div class="form-area">
                        <p class="form-area-title mb-4">Potepan Shareでまだ体験したことない旅をしよう</p>

                        <%= search_form_for  @q, url: rooms_home_path do |f| %>
 <%= f.label :address_cont, '場所の検索' %>
  <%= f.search_field :address_cont, placeholder: "場所入力" %>
  <%= f.submit '検索', class: "btn" %><br>
  <%= f.label :room_name_cont, 'キーワード検索' %>
                     <%=f.search_field :room_name_or_address_or_price_cont, placeholder: "キーワード検索"%>
                     <%= f.submit '検索', class: "btn" %>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="panel-area m-5">
            <h1 class="section-title">おすすめのエリア</h1>
            <div class="row02">
                <div class="panel-item col-lg-lg-3 col-6">
                   <span>東京</span>
                      <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/tokyo.jpg", size: "200x350"),rooms_home_path(q: {address_cont: "東京"})%>


                    <div class="shadow"></div>
                </div>

                <div class="panel-item col-lg-lg-3 col-6">
                    <span>大阪</span>
                    <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/osaka.jpg", size: "200x350"),rooms_home_path(q: {address_cont: "大阪"})%>

                    <div class="shadow"></div>
                </div>

                <div class="panel-item col-lg-lg-3 col-6">
                    <span>京都</span>
                    <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/kyoto.jpg" , size: "200x350"),rooms_home_path(q: {address_cont: "京都"})%>

                    <div class="shadow"></div>
                </div>

                <div class="panel-item col-lg-lg-3 col-6">
                    <span>札幌</span>
                <%= link_to image_tag("https://rails-02-sample.herokuapp.com/assets/home/recommend-area/sapporo.jpg" , size: "200x350"),rooms_home_path(q: {address_cont: "札幌"})%>


                    <div class="shadow"></div>
                </div>

            </div>
        </div>

    </div>
    <%end%>

app/views/users/profile.html.erb
<div class="container-fiuld user">
    <div class="row">

<div class="container-fiuld user">
    <div class="row">
        <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
            <ul>
                <li class="">
                    <%= link_to "アカウント",users_account_path %>
                </li>

        </div>



        <div class="col-md-10 user-view">
            <div class="user-view-box">
                <div class="update-content">
                    <div class="row">
                        <h5>プロフィール</h5>
                    </div>
                </div>

                <%= form_with model: @user do |f| %>


                <div class="update-content">
                    <div class="row">
                        <div class="col-md-6 offset-md-3" %>
                            <div class="icon-box">

                                <% if @user.image.attached? %>
                                    <%= image_tag @user.image,class:"icon-image host-icon" ,size: "300x250" %>

                                <% else %>
                                    <img src="https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png" width="100" height="100" >
                                <% end %>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="update-content">
                    <div class="row">
                       <th>アイコン画像</th>

                        <%= f.file_field :image,class:"mb-4 col-md-9"  %>
                    </div>

                </div>

                <div class="update-content">
                    <div class="row">
                        <%= f.label :name,"名前",class:"col-md-3 required-a" %>
                        <%= f.text_field :name,placeholder:"名前を入力", class:"form-control col-md-9 mb-4" %>
                    </div>

                </div>

                <div class="update-content">
                    <div class="row">
                        <%= f.label :profile,"自己紹介",class:"col-md-3 required-a" %>
                        <%= f.text_area :profile,rows:"5",placeholder:"自己紹介を入力", class:"form-control mb-4 col-md-9" %>
                    </div>

                </div>


                <div class="update-content">
                    <div class="row">
                        <%= f.submit "更新" ,class:"col-md-2 btn btn-primary mx-3"%>
                    </div>
                </div>

                <% end %>

            </div>
        </div>
    </div>
</div>