config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  get 'users/profile'

  get 'rooms/home'

  devise_for :users
  get 'pages/home'
  get 'rooms/new'
  get 'reservations/index'
  get 'rooms/index'
  get 'users/login'


  resources :rooms do
    collection do
      get 'serch'
    end
  end

  resources :pages do
    collection do
      get 'home'
    end
  end

  resources :users
  resources :reservations
  resources :rooms

  resources :rooms do
    resources :reservations
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_one_attached :image
  validates :room_name, presence: true
  validates :image, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :introduction, presence: true

  def self.room_serach(search)
   Room.where(['title LIKE ?', "%#{search}%"])
end

has_many :reservations
belongs_to :user,optional: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only: [:home, :serch]

  before_action :authenticate_user!

    def index
      @rooms = Room.all
      @user = current_user
    end

    def  post
      @rooms = Room.all
    end

    def new
      @user = current_user
      @room = Room.new
    end

    def create
      @user = current_user
      @room = Room.create!(room_params)
      p 'ブレークポイントによって止まりました１'
      if @room.save
        p 'ブレークポイントによって止まりました2'
        redirect_to @room #＠roomとすることでDBから取得したデータを指定すると、そのコントローラーのshowアクションに該当するページに遷移する。「redirect_to パラメータ」
     else
       render "new"
     end
   end
   def serch
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
    @user = current_user


  end
  def home

    @room = @q.result
    @user = current_user

  end
    def show

      @user = current_user
      @reservation = Reservation.new
      @room = Room.find(params[:id])

    end




    private
    def  set_q

      @q = Room.ransack(params[:q])
    end

    def room_params
      params.require(:room).permit(:room_name, :introduction,:price,:address,:image)
    end
  end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/home.html.erb
<table>
<thead>
<tr>
<th>ルーム画像</th>
<th>ルーム名</th>
<th>場所</th>
<th>料金</th>
</tr>
<tbody>
 <% @room.each do |room| %>
<tr>
<td><% if room.image.attached? %>
 <%= image_tag room.image ,size: "300x250" %>
<% end %></td>
<td><%= room.room_name %></td>
<td>  <%= room.address %></td>
<td> <%= room.price %> </td>
<% end %>
</tbody>
</thead>
</table>

app/views/rooms/index.html.erb
<h2>登録済みルーム一覧</h2>
<table>
<thead>

<div class = "inner">
<tr>

<th>ルーム画像</th>
<th>ルーム名</th>
<th>ルーム紹介</th>
<th>料金</th>
<th>作成日</th>

</tr>
</div>

</thead>
<tbody>

<% @rooms. each do |room| %>

<tr>
<td>

<!-- <%= image_tag 'image.jpg' %>
<img src="./image.jpg" width='50%' height='100%'> -->
<%= image_tag room.image ,size: "300x250" if room.image.present? %><!--この文がdbから写真画像を表示させている -->



<div class = "name">
<td><%= link_to "#{room.room_name}", {controller: 'rooms', action: 'show', id: room.id} %> </td></div>
<td> <%= room.introduction %></td>
<td> <%= room.price %> </td>
<td> <%= room.created_at.to_s(:datetime_jp) %></td>
<tr>
<% end %>
</tbody>

app/views/rooms/new.html.erb
<%= alert %>
<div class="container-fiuld room-new">
    <div class="row">


        <div class="col-md-10 room-view">
            <div class="room-view-box">
                <%= form_with model: @room, local: true do |f| %>


                <div class="update-content">
                    <div class="row">
                        <h5>ルーム情報登録</h5>
                    </div>
                </div>

                <div class="update-content">
                    <div class="row">
                        <%= f.label :room_name,"ルーム名",class:"col-md-3 required-a" %>
                        <%= f.text_field :room_name,placeholder:"ルーム名を入力", class:"form-control col-md-9 mb-4 field_wieth_error" %>
                    </div>

                </div>

                <div class="update-content">
                    <div class="row">
                        <%= f.label :introduction,"ルーム紹介",class:"col-md-3 required-a" %>
                        <%= f.text_field :introduction,placeholder:"ルーム紹介を入力", class:"form-control col-md-9 mb-4 field_wieth_error" %>
                    </div>

                </div>

                <div class="update-content">
                    <div class="row">
                        <%= f.label :price,"料金",class:"col-md-3 required-a" %>
                        <%= f.number_field :price,placeholder:"一日の料金を入力", class:"form-control mb-4 col-md-9 field_wieth_error" %>
                    </div>

                </div>

                <div class="update-content">
                    <div class="row">
                        <%= f.label :address,"住所",class:"col-md-3 required-a" %>
                        <%= f.text_field :address,placeholder:"住所を入力", class:"form-control mb-4 col-md-9 field_wieth_error" %>
                    </div>

                </div>

                <div class="update-content">
                    <div class="row">
                        <%= f.label :image,"ルーム画像",class:"col-md-3 required-a" %>
                        <%= f.file_field :image %>
                    </div>

                </div>

                <div class="update-content">
                    <div class="row">
                        <%= f.submit "登録" ,class:"col-md-2 btn btn-primary mx-3"%>
                    </div>
                </div>

                <% end %>

            </div>
        </div>
    </div>
</div>

app/views/rooms/serch.html.erb
<html><head>
    <title>ログイン済み</title>
    <meta name="csrf-param" content="authenticity_token">
<meta name="csrf-token" content="AYhdC2x1x3LOLxi+EsSuEySDB2cTzOSGcqSfGTtfB+6k+Kyw8tW59zhf9Mya83ky32Fm2jMnHmbEtOsIcC+x4g==">

  </head>

  <body>
    <header class="header">

        <a href="/"><img alt="サイトのロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>

 <a class="btn btn-primary my-2 mx-3" href="/users/sign_in">ログイン</a>
<a class="btn btn-secondary" href="/users/sign_up">登録する</a>
</header>


<script>
  $(function() {
    $('.nav-trigger').click(function() {
          $('.header-nav-menu').toggle(1500);
      })
  });
</script>

  <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>


<%= search_form_for  @q, url: rooms_home_path do |f| %>
 <%= f.label :address_cont, '場所の検索' %>
  <%= f.search_field :address_cont %>
  <%= f.submit '検索', class: "btn" %>
<%end%>
            <h1 class="section-title">おすすめのエリア</h1>

                    <span>東京</span>
                    <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E6%9D%B1%E4%BA%AC"><img class="panel-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg"></a>



                    <span>大阪</span>
                    <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E5%A4%A7%E9%98%AA"><img class="panel-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg"></a>


                    <span>京都</span>
                    <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E4%BA%AC%E9%83%BD"><img class="panel-image shadow" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg"></a>

                    <span>札幌</span>
                    <a href="https://presite-potepancamp-rails-02.herokuapp.com/rooms/search?area=%E6%9C%AD%E5%B9%8C"><img class="panel-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg"></a>
                    <div class="shadow">
    <footer class="footer">
    <p>© 2020 POTEPAN.INC.</p>
</footer>

</body></html>

app/views/rooms/show.html.erb
        <% if @room.image.attached? %>
        <%= image_tag @room.image ,size: "300x250" %>
        <% end %>
        <% if @user.image.attached? %>
         <%= image_tag @user.image,class:"icon-image host-icon" ,size: "300x250" %>
         <% else %>
         <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg"  alt='アイコン画像' class="icon-image host-icon" width="100" height="100" >
        <% end %><br>

                    部屋の名前:
                    <%= @room.room_name %><br>
                    場所：
                    <%= @room.address %><br>
                    部屋の紹介：
                    <%= @room.introduction %><br>

         <%= form_with model: @reservation, method: :get, url: new_room_reservation_path(@room.id) do |f| %>
         <!--(@room.id)はactioncontroller エラーで、missing required keys:room_idと記載があったため、(room_idが必要だけどないよっと言われている)roomのidをpshtに渡す必要があるため、roomのidで＠room_id　。
         ちなみに、bookとroomのidが必要と言われれば、(@book, room.id)と記載 -->
                <%= f.hidden_field :room_id, :value => @room.id %>
                <%= f.label :room_id ,"部屋ID"%>
                <h5 class="price-icon"><%= @room.price %> / １日（1泊の金額）</h5>
                <!--　一泊の金額 -->
                    <div class="room-show-date-select">
                        <%= f.label :room_id ,"部屋ID"%>
                        <p><%= @room.id%>/ID</p> <br>
                        <%= f.label :start_date ,"開始日"%>
                        <%= f.date_field :start_date ,class:"form-control mb-4" %>
                        <%= f.label :end_date ,"終了日"%>
                        <%= f.date_field :end_date ,class:"form-control mb-4" %>
                        <%= f.label :people ,"人数"%>
                        <%= f.number_field :people ,class:"form-control mb-4" %>
                        <%= f.submit "予約する",class:"form-control btn btn-primary"%>
                    </div>
                <% end %>