config/routes.rb
Rails.application.routes.draw do
  get 'users/account'
  get 'users/profile'

  get 'rooms/home'

  devise_for :users
  get 'pages/home'
  get 'rooms/new'
  get 'reservations/index'
  get 'rooms/index'
  get 'users/login'


  resources :rooms do
    collection do
      get 'serch'
    end
  end

  resources :pages do
    collection do
      get 'home'
    end
  end

  resources :users
  resources :reservations
  resources :rooms

  resources :rooms do
    resources :reservations
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>



  <head>
    <title>Booking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
  <div class =color>

   <a href="/users/login"><img alt="サイトのロゴ画像" src=https://rails-02-sample.herokuapp.com/assets/common/logo.png width="25%" height="70%"></a>

</div>
  <ul class = "head">
  <li><a href = "/users/login">
<% if @user.image.attached? %>
         <%= image_tag @user.image,class:"icon-image host-icon" ,size: "50x50" %>
         <% else %>
         <img src="https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png"  alt='アイコン画像' class="icon-image host-icon" width="120" height="120" >
        <% end %></li></a>
        <%= @user.name %>
<ul class="list_navi">
<li class="menu_li"><%= link_to "ルーム登録", rooms_new_path %></li>
<li class="menu_li"><%= link_to "予約済みルーム一覧", reservations_path %></li>
<li class="menu_li"><%= link_to "登録済みルーム一覧",rooms_path%></li>
<li class="menu_li"><%= link_to "設定", users_account_path %></li>
<li class="menu_li"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>

</ul>
</li>
</ul>

</header>
  <body>
    <%= yield %>
  </body>
  <br>
  <footer>
  2023.予約サイト
  </footer>
</html>

app/views/layouts/hedaer.html.erb
<ul class="g_navi">
<li><a href = "#"></li>
<li><% if @user.image.attached? %>
         <%= image_tag @user.image,class:"icon-image host-icon" ,size: "30x25" %>
         <% else %>
         <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg"  alt='アイコン画像' class="icon-image host-icon" width="10" height="10" >
        <% end %></li></a>
<ul class="list_navi">
<li class="list_navi"><a href = "rooms/new">ルーム登録</a></li>
<li class="list_navi"><a href = "rooms/index">予約済みルーム一覧</a></li>
<li class="list_navi"><a href = "reservations/index">登録済みルーム一覧</a></li>
<li class="list_navi"><a href = "users/account">設定</a></li>
<li class="list_navi"><a href = "pages/home">ログアウト</a></li>
</ul>
</li>
</ul>